config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  devise_for :users
  
  get '/news', to: 'news#index'
  get '/news/fetch', to: 'news#fetch'

  get 'api_docs', to: 'home#api_docs'
  patch 'update_news/:id', to: 'news#update', as: 'update_news'
  

  resources :news
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/news_controller.rb
require 'net/http'
require 'uri'
# how to search: http://localhost:3000/news/fetch?topic=basketball

class NewsController < ApplicationController
    before_action :authenticate_user!, only: :create

    def fetch
        topic = params[:topic] || 'technology'
        uri = URI("https://newsapi.org/v2/everything?q=#{topic}&apiKey=#{ENV['NEWS_API_KEY']}")
        response = Net::HTTP.get(uri)
        @news_stories = JSON.parse(response)['articles']
    end
    
    def index
        @saved_stories = News.all
    end

    def create
        @news = News.new(create_news_params)
      
        if @news.save
          redirect_to news_index_path
        else
          render json: @news.errors, status: :unprocessable_entity        
        end
      end

    def edit
        @news_story = News.find(params[:id])
      end

    def update
    @news_story = News.find(params[:id])

    if @news_story.update(news_params)
        redirect_to news_index_path, notice: 'News was successfully updated.'
    else
        render :edit
    end
    end

  def destroy
    @news_story = News.find(params[:id])
    @news_story.destroy

    redirect_to news_index_path
  end

  private

  def news_params
    params.require(:news).permit(:title, :author, :content, :url)
  end
  
  def create_news_params
    params.permit(:title, :author, :content, :url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/home/api_docs.html.erb
<h1>API Documentation</h1>
<p>Our API allows you to fetch and save news stories. Here's how you can use it:</p>

<h2>Fetching News Stories</h2>
<p>To fetch news stories, <%= link_to 'click here', news_fetch_path %> or make a GET request to <code>news/fetch?topic={enter topic name}</code>.</p>

<h2>Saving a News Story</h2>
<p>After fetching news stories, click the 'Save this story' button to save a news story.</p>


<h2>Updating a News Story</h2>
<p>Navigate to localhost:3000/news/:id/edit, where :id is the ID of the news story, to update a news story.</p>

<h2>Deleting a News Story</h2>
<p>Navigate to localhost:3000/news/:id, where :id is the ID of the news story, and click the 'Delete' button to delete a news story.</p>

app/views/home/index.html.erb
<h1>Welcome to the News API</h1>
<p>This API allows you to fetch and save news stories. Here's how you can use it:</p>
<ul>
<li>To fetch news stories, <%= link_to 'click here', news_fetch_path %> or make a GET request to <code>news/fetch?topic={enter topic name}</code>.</li>

</ul>
<p>For more details, check out our <a href="/api_docs">API documentation</a>.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewsApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <%= message %>
      </div>
    <% end %>

    <nav>
      <%= link_to 'Home', root_path %>
      <% if current_user %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Login', new_user_session_path %>
        <%= link_to 'Sign up', new_user_registration_path %>

      <% end %>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/news/edit.html.erb
<% p @news_story %>

<%= form_for @news_story, url: update_news_path(@news_story), method: :patch do |form| %>
    <div>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :author %>
        <%= form.text_area :author %>
    </div>
  
    <div>
      <%= form.label :content %>
      <%= form.text_area :content %>
    </div>
  
    <div>
      <%= form.label :url %>
      <%= form.text_field :url %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
<% end %>

app/views/news/fetch.html.erb
<% @news_stories.each do |story| %>
    <h2><%= story['title'] %></h2>
    <p><%= story['content'] %></p>
    <p><a href="<%= story['url'] %>">Read more</a></p>

    <% if user_signed_in? %>
        <%= form_with(url: news_index_path, method: :post) do %>
            <%= hidden_field_tag :title, story['title'] %>
            <%= hidden_field_tag :author, story['author'] %>
            <%= hidden_field_tag :content, story['content'] %>
            <%= hidden_field_tag :url, story['url'] %>
            <%= submit_tag 'Save this story' %>
        <% end %>
    <% else %>
        <p><a href="<%= new_user_session_path %>">Login</a> to save this story</p>
    <% end %>
<% end %>

app/views/news/index.html.erb
<% @saved_stories.each do |story| %>
  <h2><%= story.title %></h2>
  <p><%= story.content %></p>
  <p><a href="<%= story.url %>">Read more</a></p>
  <%= link_to 'Edit', edit_news_path(story) %>
  <%= button_to 'Delete', { action: "destroy", id: story.id }, method: :delete %>
<% end %>